### ISSUE TITLE
Create network diagram of connection, for each example

### ISSUE THREAD

**Issue by Karabiy** [vponoikoait/k8s-network-policies#2]
For each network policy compose interactive diagram which represets its behaviour. Make it clickable, so people can click for example on bad-apple-app1 and on google to see if **'Connection is permitted'**, **'Connection is blocked by Network policy'** 
![Image](https://github.com/user-attachments/assets/b6f71354-c1f0-4c70-8ed0-c08f2b760f40)
Configuration of scuh objects should stay separate, and preferrably be represted in yaml file 
maybe something like 

```yaml
bad-apple-app1:
  connection_allowed: 
    - google 
google: 
```
